# Site settings
title: Bigbluedev Blog
email: michael@bigbluedev.com
description: > # this means to ignore newlines until "baseurl:"
  Experiments in using the docker ecosystem to create a DIY hosting platform
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.bigbluedev.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
permalink: none

# Build settings
markdown: kramdown

kramdown: 
  input: GFM

gems:
  - jekyll-compass
